### ISSUE TITLE
Unable to configure the Custom CSS extension

### ISSUE THREAD

**Issue by misaligar** [FreshRSS/Extensions#182]
**Error message:** 

Your CSS file is not writable, please change the file permissions for xExtension-CustomCSS/static/

**Screenshot:**

![image](https://github.com/FreshRSS/Extensions/assets/42714627/a0abc33f-036f-45eb-878a-67d7588f5fdd)

**Installation Details:**

Host: debian 12
FreshRSS: Docker latest installed from https://hub.docker.com/r/freshrss/freshrss
System: Intel N100

**Docker Compose:**

```
version: "3.8"
services:
  freshrss:
    network_mode: bridge
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
      CRON_MIN: '2,32'
    image: freshrss/freshrss:latest
    container_name: freshrss
    ports:
      - 8080:80
    restart: always
    volumes:
      - /home/lab/Docker/AppData/freshrss/data:/var/www/FreshRSS/data
      - /home/lab/Docker/AppData/freshrss/extensions:/var/www/FreshRSS/extensions

```

**Volume Permissions:**

```
drwxr-xr-x 4 lab 4.0K Nov 16 22:49 .
drwxr-xr-x 7 lab 4.0K Nov 16 19:15 ..
drwxrwxr-x 9 lab 4.0K Nov 16 22:53 data
drwxr-xr-x 3 lab 4.0K Nov 18 09:19 extensions


drwxr-xr-x 4 lab 4.0K Oct 31 07:17 xExtension-CustomCSS


drwxr-xr-x 4 lab 4.0K Oct 31 07:17 .
drwxr-xr-x 3 lab 4.0K Nov 18 09:19 ..
-rw-r--r-- 1 lab  943 Oct 31 07:17 configure.phtml
-rw-r--r-- 1 lab  32K Oct 31 07:17 desktop_resolution.png
-rw-r--r-- 1 lab 1.3K Oct 31 07:17 extension.php
drwxr-xr-x 5 lab 4.0K Oct 31 07:17 i18n
-rw-r--r-- 1 lab  34K Oct 31 07:17 LICENSE
-rw-r--r-- 1 lab  207 Oct 31 07:17 metadata.json
-rw-r--r-- 1 lab  18K Oct 31 07:17 mobile_resolution.png
-rw-r--r-- 1 lab 2.4K Oct 31 07:17 README.md
drwxr-xr-x 2 lab 4.0K Oct 31 07:17 static
```

**User ID:**

```
lab@homelab:~/Docker/AppData/freshrss/extensions/xExtension-CustomCSS$ id
uid=1000(lab) gid=1000(lab) ...
```
