### ISSUE TITLE
Multiline titles - working CSS code included

### ISSUE THREAD

**Issue by tiborepcek** [FreshRSS/Extensions#46]
Hi, i only want to share working CSS code from @Frenzie ([issue #2344](https://github.com/FreshRSS/FreshRSS/issues/2344) in main FreshRSS ), thanks to i can read whole (long) titles in multiple lines right from RSS feeds on desktop and mobile. So here is the CSS code:

```css
.horizontal-list{display:flex;flex-wrap:wrap}
.flux .item > a {white-space:normal}
.flux:not(.current):hover .item.title {position:relative;max-width:inherit}
.item:last-child{margin-left:auto}
```
